<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>SatsumaFrontWindowTint</AssemblyName>
    <RootNamespace>SatsumaFrontWindowTint</RootNamespace>
    <OutputPath>bin\Release\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="MSCLoader">
      <HintPath>MSCLoader.dll</HintPath>
    </Reference>
    <Reference Include="MscModApi">
      <HintPath>MscModApi.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
